[package]
name = "harmony-modules"
version = "0.1.0"
edition = "2024"

[dependencies]
harmony-common = { path = "../common" }
twilight-model = "0.17"
tokio = { version = "1.52", features = ["full"] }
serde_json = "1"
tracing = "0.1"
dashmap = "5.5.3"
redis = { version = "0.27", features = ["aio", "tokio-comp"] }
futures = "0.3.32"
harmony-cache = { version = "0.1.0", path = "../cache" }
