[package]
name = "harmony-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
harmony-common = { path = "../../crates/common" }
harmony-database = { path = "../../crates/database" }
harmony-messaging = { path = "../../crates/messaging" }
harmony-modules = { path = "../../crates/modules" }
harmony-commands = { path = "../../crates/commands" }
tokio = { version = "1.52", features = ["rt-multi-thread", "macros", "signal"] }
twilight-http = "0.17"
tracing = "0.1"
tracing-subscriber = "0.3"
redis = "0.27"
rustls = { version = "0.23", features = ["ring"] }
dotenvy = "0.15.7"
harmony-cache = { version = "0.1.0", path = "../../crates/cache" }
