[workspace]
members = [
    "crates/common",
    "crates/database",
    "crates/cache",
    "crates/messaging",
    "crates/gateway",
    "crates/commands",
    "apps/bot", "crates/modules", "apps/api",
]
default-members = ["apps/bot"]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
