[package]
name = "railway-modules-registry"
version = "0.1.0"
edition = "2021"

[dependencies]
railway-common = { path = "../../common" }
railway-antinuke = { path = "../antinuke" }
railway-database = { path = "../../database" }
twilight-http = "0.17"
tokio = { version = "1.52", features = ["full"] }
thiserror = "2"
