[package]
name = "railway-automod"
version = "0.1.0"
edition = "2021"

[dependencies]
railway-common = { path = "../../common" }
railway-database = { path = "../../database" }
railway-cache = { path = "../../cache" }
twilight-model = "0.17"
tracing = "0.1"
tokio = { version = "1.52", features = ["full"] }
