[package]
name = "harmony-commands"
version = "0.1.0"
edition = "2024"

[dependencies]
harmony-common = { path = "../common" }
harmony-database = { path = "../database" }
harmony-cache = { path = "../cache" }
harmony-modules = { path = "../modules" }
tokio = { version = "1.52", features = ["sync"] }
thiserror = "2"
tracing = "0.1"
serde_json = "1"
twilight-model = "0.17"
twilight-http = "0.17"
twilight-util = { version = "0.17", features = ["builder"] }
chrono = { version = "0.4", features = ["serde"] }
lavende = { git = "https://github.com/waris4ly/lavende", branch = "dev" }
uuid = { version = "1.23.4", features = ["v4"] }
redis = { version = "0.27", features = ["tokio-comp", "aio"] }

