version: '29.6.1'

services:
  postgres:
    image: postgres:18-alpine
    container_name: railway-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=waris
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata18:/var/lib/postgresql
    networks:
      - railway-network

  redis:
    image: redis:8.8.0-alpine
    container_name: railway-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - railway-network

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: railway-bot
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgresql://waris@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - railway-network

volumes:
  pgdata18:
  redisdata:

networks:
  railway-network:
    driver: bridge
